export const SIGN_IN_USER = "SIGN_IN_USER";
export const SIGN_UP_USER = "SIGN_UP_USER";

export const SET_PROJECTS = "SET_PROJECTS";
export const SET_COMPLETED_PROJECTS = "SET_COMPLETED_PROJECTS";
