export const SIGN_IN_USER = "SIGN_IN_USER";
export const SIGN_UP_USER = "SIGN_UP_USER";

export const SET_PROJECTS = "SET_PROJECTS";
export const SET_COMPLETED_PROJECTS = "SET_COMPLETED_PROJECTS";

export const SET_DEVELOPERS = "SET_DEVELOPERS";
export const SET_TECH_STACK = "SET_TECH_STACK";

export const SET_DASHBOARD_DATA = "SET_DASHBOARD_DATA";
